services:
  # postgres service removed - using external DB_URL instead

  api:
    build: ./api  # Will be replaced by deploy.yml with ECR image
    environment:
      DB_URL: ${DB_URL}
      SERVER_PORT: 8080
      DIVVY_STATION_INFO_URL: "https://gbfs.lyft.com/gbfs/2.3/chi/en/station_information.json"
      DIVVY_STATION_STATUS_URL: "https://gbfs.lyft.com/gbfs/2.3/chi/en/station_status.json"
      ML_SERVICE_URL: "http://ml:5000"
      ML_REQUEST_TIMEOUT_MIN: ${ML_REQUEST_TIMEOUT_MIN:-5}
      ML_PORT: ${ML_PORT:-5000}
      DATA_COLLECTION_INTERVAL_MIN: ${DATA_COLLECTION_INTERVAL_MIN:-15}
      PREDICTION_INTERVAL_HOURS: ${PREDICTION_INTERVAL_HOURS:-2}

    ports:
      - "80:8080"
    depends_on:
      ml:
        condition: service_healthy
    networks:
      - divvy_network

  ml:
    build: ./ml-pipeline  # Will be replaced by deploy.yml with ECR image
    environment:
      ML_PORT: ${ML_PORT:-5000}
      DB_URL: ${DB_URL}
      AWS_REGION: ${AWS_REGION:-us-east-2}
      MODEL_S3_BUCKET: ${MODEL_S3_BUCKET}
    volumes:
      - ml_data:/app/data

    networks:
      - divvy_network
    command: ["/app/startup.sh"]
    healthcheck:
      test: ["CMD", "curl", "-f", "http://127.0.0.1:5000/health"]
      interval: 15s
      timeout: 10s
      retries: 30
      start_period: 90s

volumes:
  ml_data:

networks:
  divvy_network:
    driver: bridge